<?php

declare(strict_types=1);
/**
 *  Class representing a token class - its instances will be 
 * x
 *  - generated by Lexer and 
 *  - consumed by Parser
 * 
 * @author Sven Schrodt<sven@schrodt.club>
 * @link https://github.com/SchrodtSven/Phatman
 * @package Phatman
 * @version 0.1
 * @since 2025-08-04
 */

namespace SchrodtSven\Phatman;


final class Token
{

    public function __construct(private TokenType $mType, private string $mText) {}

    public function getType(): TokenType
    {
        return $this->mType;
    }
    public function getText()
    {
        return $this->mText;
    }

    public function __toString(): string
    {
        return $this->mText;
    }
}
